name: Product tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.12'
      - run: python -m pip install -e . setuptools wheel
      - run: python -m unittest discover -s tests -v
      - run: python -m pip install numpy==2.3.5
      - run: python -m unittest discover -s benchmarks/evaluation -p 'test_*.py' -v
      - run: python -m pip wheel --no-deps --no-build-isolation . -w dist
